apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: podinfo-resource-5
  namespace: ocm-system
spec:
  interval: 1m0s
  sourceRef:
    kind: ComponentVersion
    name: podinfo-5
    resourceRef:
      name: deployment
      version: latest
